name             'boa'
maintainer       'Elias Abacioglu'
maintainer_email 'elias.abacioglu -AT- deltaprojects -DOT- com'
license          'Apache v2.0'
description      'Installs/Configures boa'
version          '0.0.1'
